name: "Deploy to Neocities"
on: [push]
jobs:
  deploy:
    name: "Deploy to Neocities"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: bcomnes/deploy-to-neocities@v1.1.11
        with:
          api_token: ${{ secrets.NEOCITIES_TOKEN }}
          dist_dir: "."
          cleanup: false
